apiVersion: apps/v1
kind: Deployment
metadata:
  name: agilis-api
  labels:
    app: agilis-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agilis-api
  template:
    metadata:
      labels:
        app: agilis-api
    spec:
      containers:
        - name: agilis-api
          image: smokeeaasd/agilis-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: APP_PORT
              value: "3000"
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: mongodb://admin:password@mongo:27017/agilis-api?authSource=admin
            - name: JWT_SECRET
              value: 57d30e0b45f2865badafdd471249929c
            - name: JWT_EXPIRES_IN
              value: 1d